version: "3"
services:
  pgadmin:
    image: dpage/pgadmin4:8.2
    environment:
      PGADMIN_DEFAULT_EMAIL: kletka@doomer.com
      PGADMIN_DEFAULT_PASSWORD: comanche
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 1234:80
    depends_on:
      - db
  db:
    image: radebajic/moviedb
    environment:
      POSTGRES_PASSWORD: pacificdrive
    ports:
      - 5432:5432